# Generated by Django 5.0.6 on 2024-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmodel',
            name='type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
