# Generated by Django 5.0.6 on 2024-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
